name: "create-release"
author: "dev-hato Development Team"
description: "リリースを作成する"
inputs:
  github-token: # id of input
    description: "GITHUB_TOKEN"
    required: true
runs:
  using: "composite"
  steps:
    - name: Increment version
      id: increment_version
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      env:
        SHA: ${{ github.sha }}
      with:
        github-token: ${{inputs.github-token}}
        result-encoding: string
        script: |
          const script = require('${{ github.action_path }}/scripts/action/increment_version.js')
          return await script({github, context})
    - name: Create release
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      env:
        GITHUB_REF: ${{env.GITHUB_REF}}
        TAG_NAME: ${{ steps.increment_version.outputs.result }}
      with:
        github-token: ${{inputs.github-token}}
        script: |
          const script = require('${{ github.action_path }}/scripts/action/create_release.js')
          return await script({github, context})
