name: "create-release"
author: "dev-hato Development Team"
description: "リリースを作成する"
inputs:
  github-token: # id of input
    description: "GITHUB_TOKEN"
    required: true
runs:
  using: "composite"
  steps:
    - name: Increment version
      id: increment_version
      uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7.1.0
      env:
        SHA: ${{ github.sha }}
      with:
        github-token: ${{inputs.github-token}}
        result-encoding: string
        script: |
          const {script} = require('${{ github.action_path }}/dist/increment_version.js')
          return await script(github, context)
    - name: Create release
      uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7.1.0
      env:
        GITHUB_REF: ${{env.GITHUB_REF}}
        TAG_NAME: ${{ steps.increment_version.outputs.result }}
      with:
        github-token: ${{inputs.github-token}}
        script: |
          const {script} = require('${{ github.action_path }}/dist/create_release.js')
          return await script(github, context)
