---
name: create-release

on:
  push:
    branches:
      - main
    paths:
      - action.yml

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: ./
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
