---
name: create-release

on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: ./
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
